services:
  gateway:
    read_only: true
    tmpfs: [/var/cache/nginx, /var/run]
    security_opt: [no-new-privileges:true]
  hub:
    read_only: true
    tmpfs: [/var/cache/nginx, /var/run]
    security_opt: [no-new-privileges:true]
  wazuh:
    read_only: true
    tmpfs: [/var/cache/nginx, /var/run]
    security_opt: [no-new-privileges:true]
  auth-primary:
    security_opt: [no-new-privileges:true]
  defectdojo:
    security_opt: [no-new-privileges:true]
  auto-sync-status:
    security_opt: [no-new-privileges:true]
  docs:
    security_opt: [no-new-privileges:true]
